### ISSUE TITLE
Failing import of metadata from projects with version R3 2022

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#126]
Some projects with the oldest supported version R3 2022 are failing during manual migration (export > import metadata) with the following error

![image](https://github.com/user-attachments/assets/7b5194ec-dc13-4bd2-bed2-85c720e55b11)

ping @kvelikov and @niliev for a project's metadata that fully reproduces the issue.

The issue is most likely caused by missing variable references due to breaking changes in handling the IDs.

Reported through ticket 1667849

**Comment by kvelikov** [comment]
After research, it seems that the metadata is incorrect.
