### ISSUE TITLE
Logical CSS properties are not correctly displayed in the Property Grid 

### ISSUE THREAD

**Issue by grozevg** [telerik/themebuilder#13]
**Describe the bug**
The Property Grid is not displaying the logical CSS properties correctly. Some of these properties have already been added, but mappings for the "border" and "border-radius" are still missing.

**To Reproduce**
1. Open a new project
2. Drilldown to the Grid 
3. Select the whole component at the end of the frame 
4. Select the Header Cell

**Actual Results**
The "Border-width left" and "Border-width bottom" are displayed as having a value of 0.

**Expected behavior**
The "Border-width left" and "Border-width bottom" should both be displayed as having a value of 1px.

**Screenshots**
![image](https://user-images.githubusercontent.com/37333914/218080293-ce4d2089-d271-4664-b7c4-4450ec6da564.png)

**Comment by Martin-Hristov** [comment]
Border-bottom-width is correctly shown at 1px, border-left-width is shown at 0px, but that is the actual value - template and live preview
