### ISSUE TITLE
Handle inconsistent element rendering in the Grid component

### ISSUE THREAD

**Issue by grozevg** [telerik/themebuilder#14]
**Describe the bug**
The issue concerns the inconsistent rendering of elements in the Grid. There are two discrepancies between the Kendo Angular and React implementations of the following elements:

- The table element: "k-table-md" vs "k-grid-md"
- The filter button has an extra "k-rounded-md" class (additionally, its parent element should be styleable)

Steps to reproduce: 
1. Drill down to grid template
2. Select Cell part 
3. Set background color
4. Export the project

Actual: 
The selector is **.k-grid.k-grid-md .k-grid-container .k-grid-content .k-table.k-grid-table.k-grid-md .k-table-tbody .k-master-row >td**

Expected:
The selector is **.k-grid.k-grid-md .k-grid-container .k-grid-content .k-table.k-grid-table.k-grid-md .k-table-tbody .k-master-row >td, .k-grid.k-grid-md .k-grid-container .k-grid-content .k-table.k-grid-table.k-table-md .k-table-tbody .k-master-row >td, ..., ...

**Comment by rkirilov** [comment]
We should generate both selectors since React is holding the wrong rendering. It will be fixed in React, but we cannot update the version of components and templates in the TB

**Comment by rkirilov** [comment]
This should be added in Develop branch

**Comment by kvelikov** [comment]
Findings: As a rule of thumb, we should not style *-md unless the style comes from this style itself. We should use the data-tb-selector to omit the class. 
In the particular case, the *-md style doesnt have any styles so the problem should be solved by using the data-tb-selector only

**Comment by kvelikov** [comment]
Test case: Test if ommiting the *-md leave changes hanging

**Comment by Martin-Hristov** [comment]
Still export just one selector exported: .k-grid.k-grid-md .k-grid-header .k-grid-header-wrap .k-table.k-grid-header-table

**Comment by Martin-Hristov** [comment]
The above issue is fixed, the filter button, however, is not applied still in Angular, due to rendering issue - th instead of td
