### ISSUE TITLE
Splitter collapsed splitbar templates are wrong

### ISSUE THREAD

**Issue by vstaykov** [telerik/themebuilder#17]
**Describe the bug**
Splitter collapsed splitbar templates are wrong and styles are not applied. When a collapsable and resizable splitbar is collapsed, the `k-splitbar-draggable-[horizontal/vertical]` class is removed from the element. However, the template includes this class and thus the customisations are not applied.

In addition, the icon component part in the tree on the right is named `Collapsed` but it must be 'Expand` as the template is for a collapsed pane.

**To Reproduce**
1. Go to Splitter
2. Select the collapsed template icon
3. Change the `font-size` property to 30px
4. Collapse a pane in the live preview

**Actual Results**
The icon has the default Kendo theme font-size

**Expected behavior**
The icon has font-size 30px

**Additional context**
As a pane cannot be both collapsed and resizable in the same time, the `k-splitbar-draggable-[horizontal/vertical]` is removed from the element and thus it must be removed from the template, too.

Ticket ID: 1600436

**Comment by Martin-Hristov** [comment]
Issue 1 - Better naming of icons for left and right pane

Right Icon Wrapper, Left Icon Wrapper, Up Icon Wrapper and Down Icon Wrapper give off the illusion that they are responsible for the type of icon - pointing right, left, up and down respectively. However, they actually are responsible for the icon for the pane to the right, to the left, to the top and to the bottom. And depending on wether it is collapsed or expanded the icon's direction changes but the styles persist. That is the correct behavior but the naming might be confusing. 

Name them: Right Pane Icon Wrapper, Left Pane Icon Wrapper, Top Pane Icon Wrapper, Bottom Pane Icon Wrapper
