### ISSUE TITLE
ThemeBuilder generates incorrect styles for Grid Row Hover state template

### ISSUE THREAD

**Issue by kvelikov** [telerik/themebuilder#21]
**Describe the bug**
ThemeBuilder generates incorrect styles for Grid Row Hover state template

**To Reproduce**
1. Go to Grid Row hover template
2. Change the background color to blue

**Actual Results**
The style contains an additional .k-grid-table-wrap selector

**Expected behavior**
The .k-grid-table-wrap selector should not be there.

**Comment by vstaykov** [comment]
This is fixed, could not reproduce anymore.
