### ISSUE TITLE
Incorrect rendering for the icon of the Menu component

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#29]
**Describe the bug**
The icon for the **Menu** component in Kendo UI is not rendered as expected. This, in terms, breaks the generated ThemeBuilder styles when using icon fonts (instead of SVG icons) - the issue is related to a bug in React and the TB not following the test specs (see https://github.com/telerik/kendo-react-private/issues/2874)

**To Reproduce**

1. Create a theme with an icon font
2. Apply a custom icon for the Menu

![image](https://github.com/telerik/themebuilder/assets/18008302/8627a65f-4f6a-4b11-a63a-478274205778)

![image](https://github.com/telerik/themebuilder/assets/18008302/82fa9d5c-c86b-4136-b9aa-8e57e2f41fb7)

**Actual Results**

While the in-app preview (React) shows the new icon properly, that is not the case for applications using Kendo UI for Angular.
Reason: the live preview and the React rendering are wrong https://github.com/telerik/kendo-themes/blob/develop/tests/menu/menu.html

**Expected behavior**

Icon fonts to work in Kendo UI 

**Components technology and version**
R2 2023

**Additional context**

Reported through ticket **1617701**

The issue was reported and escalated to the Kendo UI team. Once a stable fix is deployed with a new version of Kendo, we will update and close this issue.

**Comment by vstaykov** [comment]
This is fixed, could not reproduce anymore.

**Comment by Martin-Hristov** [comment]
Cannot reproduce
