### ISSUE TITLE
The TextBox component parts are missing the Button subcomponent

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#37]
**Describe the bug**
The **TextBox** component can be created with prefixes and suffixes as follows:
![image](https://github.com/telerik/themebuilder/assets/18008302/2c0bc216-3a79-4990-bbd1-505feb0ecd0a)

However, the **Button** component is missing (from the component parts section), while the **prefix** is available in the parts. As a result, any styles applied globally for the main **Button** component can not be overwritten within the prefix.

![image](https://github.com/telerik/themebuilder/assets/18008302/1ed39ae8-b8b8-428b-a0e2-4e6e40b6be7e)

**To Reproduce**
1. Advanced Edit > Button > apply border
2. Advanced Edit > TextBox > Component parts > Prefix 
![image](https://github.com/telerik/themebuilder/assets/18008302/24f307a0-024c-4e60-91f4-21e27d3d8199)
3. Try to remove the border of the prefix.

**Actual Results**
The styles applied globally on the **Button** component can't be removed for the prefix of the **TextBox** due to missing **Button** in the **component parts** section.

**Expected behavior**
To be able to overwrite the button styles.

**Components technology and version**
ThemeBuilder R2 2023

**Additional context**
Reported through t.1620998

**Comment by imtodor** [comment]
The issue will be fixed for the R3 2023 and next versions.
