### ISSUE TITLE
Material Theme uses wrong shadow values

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#52]
**Describe the bug**
New Material project in ThemeBuilder R3 2023 with Kendo Theme 7.0.0 applies incorrect drop shadows

**To Reproduce**
1. Create a new Material project
2. Compare the generated shadows of any component with the truth of the source

truth (Kendo react demo)
![image](https://github.com/telerik/themebuilder/assets/18008302/e6cd23c1-b141-4710-ac23-4060425e98ff)

result in TB
![image](https://github.com/telerik/themebuilder/assets/18008302/a7d6270a-ec2e-4792-8ce3-1553e1dfd62a)

**Expected behavior**
To implement the new elevation values for the related variables introduced in Kendo Theme 7.x.x

https://www.telerik.com/kendo-angular-ui/components/styling/theme-material/customization-shadows/

**Additional context**
Reported through t.1627571

**Comment by vstaykov** [comment]
Updates for R3 2023:
- styles maps
- Fluent effects variables values
- Material effects variables values

cc @Martin-Hristov
