### ISSUE TITLE
CheckBoxLabel is wrapped inside k-checkbox-wrap element

### ISSUE THREAD

**Issue by kvelikov** [telerik/themebuilder#61]
The Checkbox inputs are not rendered as expected for KendoReact.

There is a class mismatch between the Checkbox implementation and [test specs](https://github.com/telerik/kendo-themes/blob/develop/tests/checkbox/checkbox.html).

The CkeckBoxLabel is wrapped inside <span class="k-checkbox-wrap">

Current behavior
![image](https://github.com/telerik/kendo-react/assets/5024892/01d4fbd6-dc22-4086-afd2-dc84adaa6e80)

Expected/desired behavior
To follow the [test specs](https://github.com/telerik/kendo-themes/blob/develop/tests/checkbox/checkbox.html) the k-checkbox-label element should be outside the k-checkbox-wrap
![image](https://github.com/telerik/kendo-react/assets/5024892/08b06b28-9c3a-4df2-8cea-dae91488e1ad)

Issues:
- [ ] Issue 1: Label styles are not exported for selected components

**Comment by NickIliev** [comment]
+1 reported from t.1637764

The Angular rendering is entirely missing the `k-checkbox-wrap` selector, which in terms causes the styles not to be applied for the selected checkbox

Example here: https://stackblitz.com/edit/kendo-grid-playground-zdfujd?file=src%2Fapp%2Fapp.component.ts

**Comment by Martin-Hristov** [comment]
Issue 1: Label styles are not exported for selected components

Steps to reproduce:
1. Set the text of the label component in the Checkbox to red
2. Export 
3. Check the exported scss

Actual result: the style is not there
Epxected result: the style is successfully exported
