### ISSUE TITLE
Increase specificity for Tooltip component

### ISSUE THREAD

**Issue by Martin-Hristov** [telerik/themebuilder#62]
**Describe the bug**
The tooltip component has both k-tooltip and k-popup classes. However, ThemeBuilder selector for the exported styles is simply k-tooltip, which when combined with styles for select k-popup leads to the latter overriding the former

**To Reproduce**
1. Drilldown to Tooltip
2. Set 'red' as background color to the Tooltip template 
3. Drilldown to Color Picker
4. Select the Color Gradient View's Popup layer
5. Set its background value to 'blue'
6. Export
7. Insert the generated styles in the Dojo demo for the Tooltip - https://demos.telerik.com/kendo-ui/tooltip/index
8. Run the demo

**Actual Results**
The tooltip is blue

**Expected behavior**
The tooltip is red

**Comment by kvelikov** [comment]
This should be fixed here in Kendo UI core: https://github.com/telerik/kendo-ui-core/issues/7667
