### ISSUE TITLE
Default theme does not bind primary color correctly to all components

### ISSUE THREAD

**Issue by tgaarde** [telerik/themebuilder#70]
**Describe the bug**
A Telerik default 7.2.0 theme, does not change color of checkbox, radio and grid row selection. when editing the primary color. 

**To Reproduce**
1. Create new project, with default base
2. Change theme styles to anything
3. Change primary color
4. See the error that checkbox and slider does not share colors
5. See the error in the project settings / color list: a lot of default "orange" colors where it should have been the primary you chose

**Screenshots**
![image](https://github.com/telerik/themebuilder/assets/23551833/9092020f-1ade-437d-9b21-4b77006a27be)

**Comment by imtodor** [comment]
For a release date of the fix and a workaround of the issue until then, check this comment - https://github.com/telerik/themebuilder/issues/75#issuecomment-2098202951

**Comment by rkirilov** [comment]
Fixed in Q2 2024
