### ISSUE TITLE
Changed Kendo variable is not updated in all related components

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#75]
**Describe the bug**
When the value of some Kendo variables like $kendo-color-primary is modified through the **Edit** option, the result is applied to some components but not all that use this variable.

**To Reproduce**
1. Open a new Default theme project.
1. Select the 'kendo-color-primary' variable and use the **Edit** option
1. Change the color to **green**

As a result, the color applies for some components like **Button**, but is **not** applied for others (where the variable is used) like **Checkbox, Filter, Scheduler, Breadcrumb**, etc.
The wrong color remains active within the Template, Live Preview (React), and end application (Blazor).

**Actual Results**
![image](https://github.com/telerik/theme-builder-pro/assets/18008302/3fbc1f06-8ae5-4325-bcf0-c6e3717d3454)

**Additional context**
Reproducible with TB Q1 2024
Reported through t.1640628

**Comment by NickIliev** [comment]
+1 from t.1641211

**Comment by NickIliev** [comment]
also reported through https://github.com/telerik/themebuilder/issues/70

**Comment by imtodor** [comment]
The fix should be available within the upcoming release in the middle of May.
As a workaround until then, you could do the following:

1. Change the `$kendo-color-primary` variable to the desired color value
2. Then, go to the advanced edit of the desired component (in this case the Checkbox component)
3. Search for the `$kendo-checkbox-checked-bg` (i.e. filter the variables in the left ThemeStyles pane) and open it for editing
4. Set the `$kendo-checkbox-checked-bg`'s value to the `$kendo-color-primary`

**Comment by rkirilov** [comment]
Fixed in Q2 2024
