### ISSUE TITLE
The component part link to main component (Input) does not work

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#76]
**Describe the bug**

**To Reproduce**
1. Go to 'DropDownButton' > `Filter List Item` > 'Normal' > 'Input Container' 
2. Try to follow the link to the main component (Input)

**Actual Results**
![image](https://github.com/telerik/theme-builder-pro/assets/18008302/8742a0fc-c647-4f92-a91f-ee685e0ab491)

**Additional context**
Reproducible with TB Q1 2024
reported through t.1640178

Also reproducible with other links leading to the Input component (e.g. the SplitButton)

**Comment by NickIliev** [comment]
+1 from t.1644941

**Comment by rkirilov** [comment]
Fixed in Q2 2024
