### ISSUE TITLE
Kendo variables are not applied for all components (reproducible with several Kendo themes)

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#85]
**Describe the bug**
Creating a new Bootstrap project with a Dark theme (like Kendo Bootstrap Dark 3) results in a theme where some components are not respect the dark Kendo variables.

**To Reproduce**
1. Create a new Bootstrap project with **Kendo Bootstrap Dark 3**
2. Observe the styles for components like TileLayout, ColorGradient, Card, BottomNavigation, Breadcrumb, TreeList

**Actual Results**
Some of the components are not styled with the dark theme variables. For example, the following variables are set in the properties but are not respected:
$kendo-component-bg
$$kendo-component-text
![image](https://github.com/telerik/themebuilder/assets/18008302/5697a67b-b96a-4b82-b534-c90200cba94e)

**Components technology and version**
TB Q1 2024

**Additional context**
reported through t.1643072

related to https://github.com/telerik/theme-builder-pro/issues/2458

possibly related to https://github.com/telerik/themebuilder/issues/75
https://github.com/telerik/themebuilder/issues/70

**Comment by NickIliev** [comment]
+1 from t1644249 - reproduced with the Default theme

**Comment by NickIliev** [comment]
+1 from t1640490 (material theme)

**Comment by NickIliev** [comment]
+ 1 from shared directly through internal communication (LCARS)

**Comment by rkirilov** [comment]
Fixed in Q2 2024
