### ISSUE TITLE
Border spacing property values not applied

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#86]
**Describe the bug**
The properties for **Border Spacing** are not applied or reverted when a 0px value is being used.

**To Reproduce**

1. Set the **Border Collapse** property to **Separate** (any component that supports the property).
1. Try applying two different values for vertical and horizontal spacing in the **Table** > **Border Spacing** property. If necessary, apply a visible border to cells to better see the issue. Then revert the horizontal property to 0px.

As a result, the vertical property is also reverted to 0px.

There are four cases after editing:
```
**(>0 ; >0)** => seems to work
**(>0 ; 0)** => both set to zero if the second value was last edited and changed to zero (no matter the old value). But it is possible to bypass the bug by setting both value to zero and then setting the first value.
**(0 ; >0)** => both set to zero if the first value was last edited and changed to zero (no matter the old value). But it is possible to bypass the bug by setting both value to zero and then setting the second value.
**(0 ; 0)** => seems to work
```

**Expected behavior**
To be able to set 0px border spacing for one property without affecting the other one.

**Components technology and version**
TB Q1 2024

**Additional context**
Reported through t.1643316

**Comment by rkirilov** [comment]
Fixed in Q2 2024
