### ISSUE TITLE
Implicitly using custom fonts from the default-typography is not applied

### ISSUE THREAD

**Issue by Martin-Hristov** [telerik/themebuilder#9]
**Describe the bug**
In components where the font-family is implicitly set through the $default-typography an it uses custom fonts the proper prefixes are not applied and so the style is not applied

**To Reproduce**
1. Create a bootstrap project
2. Add a custom font
3. Set it as font-family to the $default-typography variable
4. Drill down to Chip
5. Inspect the local properties in the Text Editor

**Actual Results**
The Font-family input displays the custom font from the $default-typography variable, but the font actually used in the templates and in the Live Preview is different

**Expected behavior**
The font used in the templates and in the Live Preview is the one stated in the local properties of the Text Editor

- [x] issue 1 - Fonts with space in their name are not applied in default typography
- [x] Issue 2 - TB prefixed fonts are displayed as not installed
- [x] Issue 3 - 5.8.0 projects don't automatically apply the font
- [x] Issue 4 - 5.8.0 projects receive an additional variable

**Comment by Martin-Hristov** [comment]
issue 1 - Fonts with space in their name are not applied in default typography

Steps to reproduce:
1. Upload a font with a space in its name
2. Set it as font family for the default typography
3. Check the components

Expected result: The font is applied to the components
Actual result: it is not

**Comment by Martin-Hristov** [comment]
Issue 2 - TB prefixed fonts are displayed as not installed

Steps to reproduce:
1. Set a custom font to a default typography
2. Open the button and inspect the Local properties in the text editor

Actual result: the font is marked as not installed, it is displayed with a TB_ prefix
Expected result: the font is not prefixed with TB_ in the editor and the validation happens against its actual name

**Comment by Martin-Hristov** [comment]
Issue 3 - 5.8.0 projects don't automatically apply the font

Steps to reproduce:
1. Create 5.8.0 project
2. Set default typography with a custom font - because of the original issue, it would not take effect
3. Install the new branch
4. Check the old project

Expected result: the font is applied
Actual result: the font is not applied

This works for Fluent

**Comment by Martin-Hristov** [comment]
Issue 4 - 5.8.0 projects receive an additional variable

Steps to reproduce:
1. Create 5.8.0 project with default theme
2. Set default typography with a custom font - because of the original issue, it would not take effect
3. Install the new branch
4. Check the old project

Expected result: only the default-typography variable is present
Actual result: default-typography and kendo-default-typography exist and the second one actually gives the styles

**Comment by imtodor** [comment]
> Issue 3 - 5.8.0 projects don't automatically apply the font
> 
> Steps to reproduce:
> 
> 1. Create 5.8.0 project
> 2. Set default typography with a custom font - because of the original issue, it would not take effect
> 3. Install the new branch
> 4. Check the old project
> 
> Expected result: the font is applied Actual result: the font is not applied
> 
> This works for Fluent

Yes - it cannot be automatically applied. Thus, you should **re-apply** the changes to the `default-typography` variable (i.e. trigger a font-family change for it, so it can be processed and persisted server-side). For example, change the font family to 'Arial' and then back to your custom font. 

Once this has been done, everything should work as expected.
