### ISSUE TITLE
The Styles Editor shows metadata IDs instead of variable names

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#97]
**Describe the bug**
The Styles Editor shows metadata IDs instead of variable names

**To Reproduce**
Use the following demo project: https://themebuilderapp.telerik.com/projects/667d091ec814ef19d41a1553
and inspect the Style Editor for the **Button** > **(span) Text** component

**Actual Results**
![image](https://github.com/telerik/themebuilder/assets/18008302/62b759fd-924d-4e05-beec-50bc56832f1a)

**Components technology and version**
Reproducible with Q2 2024

**Additional context**
Reported through t.1655307

**Comment by Martin-Hristov** [comment]
Issue cannot be reproduced anymore. The shared project is no longer shared. I have tested basic scenarios to check if anything is broken and found nothing erroneous.
