### ISSUE TITLE
Add text-transform Property to Typography Tokens in ThemeBuilder

### ISSUE THREAD

**Issue by grozevg** [telerik/themebuilder#98]
**Describe the bug**
Currently, ThemeBuilder does not support the inclusion of the text-transform property within typography tokens. This limitation prevents users from applying text transformations (e.g., uppercase, lowercase) directly within the typography token settings.

**To Reproduce**
1. Open ThemeBuilder and create a new project.
2. Drill-down to any Component
3. Try adding both typography and text-transform in Styles Editor
4. See the error

**Expected Behavior**
The Text-transform Property to be part of the Typography

**Screenshots**
![image](https://github.com/telerik/themebuilder/assets/37333914/000e93e7-e05b-41bc-b8be-846a498fe7b2)

**Additional context**
Reported through t.1657634

- [ ] Issue 1 - Underline and Strikethrough decorations are not added to the _tokens.scss file

**Comment by Martin-Hristov** [comment]
Issue 1 - Underline and Strikethrough decorations are not added to the _tokens.scss file

1. Add Underline, Italic and Strikethrough decorations to a typography
2. Export
3. Check the _tokens.scss file

Actual result: only the italic decoration is present
Expected: all decorations are present
