### ISSUE TITLE
Validation error when trying to make any change to a background-image with Data URL

### ISSUE THREAD

**Issue by NickIliev** [telerik/themebuilder#99]
**Describe the bug**
The Checkbox component has a default background-image set to Data URL
![image](https://github.com/user-attachments/assets/d645ebc3-340e-498e-980d-f7e719939145)

However, with Q2 2024, we can no longer modify the Data URL through the Properties editor. Any change will be immediately reverted to the default value.

In case the change is made explicitly through Styles Editor, there will be a validation error.

![image](https://github.com/user-attachments/assets/954168b5-a7fe-4baf-a796-25319c1db5f9)

**To Reproduce**
1. Go to 'Checkbox' > `Selected` > 'Inout Box'
2. Try to change the DATA URL within the Background Image property
OR 
1. Go to 'Checkbox' > `Selected` > 'Inout Box'
2.  Set a custom color for the Background -e.g., orange (leave the data url)
![image](https://github.com/user-attachments/assets/1ac8a231-2cce-43fd-9a48-5b7a34cf60ff)
3. Load the "Styles Editor" and try to change the Data URL value for the background-image (e.g., add and immediately remove a white space)

As a result, the validation error appears, and the change can't be applied. Note that there no need for an actual change - even selecting the value triggers the validation error and prevents any further changes from being applied.
![image](https://github.com/user-attachments/assets/df0c896a-187c-4547-bf9a-0de531f3c527)

**Actual Results**
The data URL can't be modified.

**Expected behavior**
To be able to set the custom Data URL within the Checkbox component.

**Screenshots**
![image](https://github.com/user-attachments/assets/a7fc1839-da95-492c-a0f8-4aae6ff7af99)

**Components technology and version**
TB Q2 2024

**Additional context**
Reported through internal communication with TB client.

**Comment by rkirilov** [comment]
Consider also following scenario: background-image: url("https://www.telerik.com/design-system/docs/images/templates-healthcare-admin-page-header-image-v2.png");

**Comment by rkirilov** [comment]
Also consider supporting background-image: url("https://www.telerik.com/design-system/docs/images/templates-healthcare-admin-page-header-image-v2.png"); css in the uploaded external css files.

**Comment by kvelikov** [comment]
Note that backgroundEditor supports only SVG data url. The styles editor, however, supports all kind of urls.

**Comment by NickIliev** [comment]
+1 from t.1661584
